export const f1_teams = [
  {
    id: "f1_ferrari",
    name: "Ferrari",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/ferrari-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_mercedes",
    name: "Mercedes",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/mercedes-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_red_bull_racing",
    name: "Red Bull Racing",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/red-bull-racing-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_mcclaren",
    name: "McClaren",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/mclaren-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_alpine",
    name: "Alpine",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alpine-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_alfa_romeo",
    name: "Alfa Romeo",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alfa-romeo-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_haas",
    name: "Haas F1 Team",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/haas-f1-team-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_alphatauri",
    name: "AlphaTauri",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alphatauri-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_williams",
    name: "Williams",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/williams-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_aston_martin",
    name: "Aston Martin",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/aston-martin-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_f2",
    name: "F2",
    isSelected: false,
    owner: "",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1f/Formula_2_logo.svg/440px-Formula_2_logo.svg.png",
  },
];

export const nfl_teams = [
  {
    id: "f1_ferrari",
    name: "Ferrari",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/ferrari-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_mercedes",
    name: "Mercedes",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/mercedes-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_red_bull_racing",
    name: "Red Bull Racing",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/red-bull-racing-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_mcclaren",
    name: "McClaren",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/mclaren-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_alpine",
    name: "Alpine",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alpine-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_alfa_romeo",
    name: "Alfa Romeo",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alfa-romeo-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_haas",
    name: "Haas F1 Team",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/haas-f1-team-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_alphatauri",
    name: "AlphaTauri",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alphatauri-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_williams",
    name: "Williams",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/williams-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_aston_martin",
    name: "Aston Martin",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/aston-martin-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_f2",
    name: "F2",
    isSelected: false,
    owner: "",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1f/Formula_2_logo.svg/440px-Formula_2_logo.svg.png",
  },
];