export const f1_teams = [
  {
    id: "f1_alfa_romeo",
    name: "Alfa Romeo",
    option: "Alfa Romeo",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alfa-romeo-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_alphatauri",
    name: "AlphaTauri",
    option: "AlphaTauri",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alphatauri-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_alpine",
    name: "Alpine",
    option: "Alpine",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/alpine-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_aston_martin",
    name: "Aston Martin",
    option: "Aston Martin",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/aston-martin-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_f2",
    name: "F2",
    option: "F2",
    isSelected: false,
    owner: "",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1f/Formula_2_logo.svg/440px-Formula_2_logo.svg.png",
  },
  {
    id: "f1_ferrari",
    name: "Ferrari",
    option: "Ferrari",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/ferrari-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_haas",
    name: "Haas F1 Team",
    option: "Haas F1 Team",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/haas-f1-team-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_mercedes",
    name: "Mercedes",
    option: "Mercedes",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/mercedes-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_mcclaren",
    name: "McClaren",
    option: "McClaren",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/mclaren-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_red_bull_racing",
    name: "Red Bull Racing",
    option: "Red Bull Racing",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/red-bull-racing-logo.png.transform/2col/image.png",
  },
  {
    id: "f1_williams",
    name: "Williams",
    option: "Williams",
    isSelected: false,
    owner: "",
    logo: "https://www.formula1.com/content/dam/fom-website/teams/2022/williams-logo.png.transform/2col/image.png",
  },
];

export const nfl_teams = [
  {
    id: "nfl_Arizona",
    city: "Arizona",
    name: "Cardinals",
    option: "Cardinals",
    abr: "ARI",
    conf: "NFC",
    div: "West",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/u9fltoslqdsyao8cpm0k"
  },
  {
    id: "nfl_Atlanta",
    city: "Atlanta",
    name: "Falcons",
    option: "Falcons",
    abr: "ATL",
    conf: "NFC",
    div: "South",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/d8m7hzpsbrl6pnqht8op"
  },
  {
    id: "nfl_Baltimore",
    city: "Baltimore",
    name: "Ravens",
    option: "Ravens",
    abr: "BAL",
    conf: "AFC",
    div: "North",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/ucsdijmddsqcj1i9tddd"
  },
  {
    id: "nfl_Buffalo",
    city: "Buffalo",
    name: "Bills",
    option: "Bills",
    abr: "BUF",
    conf: "AFC",
    div: "EAST",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/giphcy6ie9mxbnldntsf"
  },
  {
    id: "nfl_Carolina",
    city: "Carolina",
    name: "Panthers",
    option: "Panthers",
    abr: "CAR",
    conf: "NFC",
    div: "South",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/ervfzgrqdpnc7lh5gqwq"
  },
  {
    id: "nfl_Cincinati",
    city: "Cincinati",
    name: "Bengals",
    option: "Bengals",
    abr: "CIN",
    conf: "AFC",
    div: "North",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/okxpteoliyayufypqalq"
  },
  {
    id: "nfl_Chicago",
    city: "Chicago",
    name: "Bears",
    option: "Bears",
    abr: "CIN",
    conf: "NFC",
    div: "North",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/ra0poq2ivwyahbaq86d2"
  },
  {
    id: "nfl_Cleveland",
    city: "Cleveland",
    name: "Browns",
    option: "Browns",
    abr: "CLE",
    conf: "AFC",
    div: "North",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/fgbn8acp4opvyxk13dcy"
  },
  {
    id: "nfl_Dallas",
    city: "Dallas",
    name: "Cowboys",
    option: "Cowboys",
    abr: "DAL",
    conf: "NFC",
    div: "East",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/ieid8hoygzdlmzo0tnf6"
  },
  {
    id: "nfl_Denver",
    city: "Denver",
    name: "Broncos",
    option: "Broncos",
    abr: "DEN",
    conf: "AFC",
    div: "West",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/t0p7m5cjdjy18rnzzqbx"
  },
  {
    id: "nfl_Detroit",
    city: "Detroit",
    name: "Lions",
    option: "Lions",
    abr: "DET",
    conf: "NFC",
    div: "North",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/ocvxwnapdvwevupe4tpr"
  },
  {
    id: "nfl_Bay",
    city: "Green Bay",
    name: "Packers",
    option: "Packers",
    abr: "GB",
    conf: "NFC",
    div: "North",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/gppfvr7n8gljgjaqux2x"
  },
  {
    id: "nfl_Houston",
    city: "Houston",
    name: "Texans",
    option: "Texans",
    abr: "HOU",
    conf: "AFC",
    div: "South",
    logo: ""
  },
  {
    id: "nfl_Indianapolis",
    city: "Indianapolis",
    name: "Colts",
    option: "Colts",
    abr: "IND",
    conf: "AFC",
    div: "South",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/bpx88i8nw4nnabuq0oob"
  },
  {
    id: "nfl_Jacksonville",
    city: "Jacksonville",
    name: "Jaquars",
    option: "Jaquars",
    abr: "JAX",
    conf: "AFC",
    div: "South",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/qycbib6ivrm9dqaexryk"
  },
  {
    id: "nfl_City",
    city: "Kansas City",
    name: "Chiefts",
    option: "Chiefts",
    abr: "KC",
    conf: "AFC",
    div: "West",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/ujshjqvmnxce8m4obmvs"
  },
  {
    id: "nfl_Miami",
    city: "Miami",
    name: "Dolphins",
    option: "Dolphins",
    abr: "MIA",
    conf: "AFC",
    div: "East",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/lits6p8ycthy9to70bnt"
  },
  {
    id: "nfl_Minnesota",
    city: "Minnesota",
    name: "Vikings",
    option: "Vikings",
    abr: "MIN",
    conf: "AFC",
    div: "North",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/teguylrnqqmfcwxvcmmz"
  },
  {
    id: "nfl_England",
    city: "New England",
    name: "Patriots",
    option: "Patriots",
    abr: "NE",
    conf: "AFC",
    div: "East",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/moyfxx3dq5pio4aiftnc"
  },
  {
    id: "nfl_Orleans",
    city: "New Orleans",
    name: "Saints",
    option: "Saints",
    abr: "NO",
    conf: "NFC",
    div: "South",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/grhjkahghjkk17v43hdx"
  },
  {
    id: "nfl_York",
    city: "New York",
    name: "Giants",
    option: "Giants",
    abr: "NYG",
    conf: "NFC",
    div: "East",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/t6mhdmgizi6qhndh8b9p"
  },
  {
    id: "nfl_New_York",
    city: "New York",
    name: "Jets",
    option: "Jets",
    abr: "NYJ",
    conf: "AFC",
    div: "East",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/ekijosiae96gektbo4iw"
  },
  {
    id: "nfl_Oakland",
    city: "Oakland",
    name: "Raiders",
    option: "Raiders",
    abr: "OAK",
    conf: "AFC",
    div: "West",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/gzcojbzcyjgubgyb6xf2"
  },
  {
    id: "nfl_Philidelphia",
    city: "Philidelphia",
    name: "Eagles",
    option: "Eagles",
    abr: "PHI",
    conf: "NFC",
    div: "East",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/puhrqgj71gobgdkdo6uq"
  },
  {
    id: "nfl_Pittsburgh",
    city: "Pittsburgh",
    name: "Steelers",
    option: "Steelers",
    abr: "PIT",
    conf: "AFC",
    div: "North",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/xujg9t3t4u5nmjgr54wx"
  },
  {
    id: "nfl_Diego",
    city: "San Diego",
    name: "Chargers",
    option: "Chargers",
    abr: "SD",
    conf: "AFC",
    div: "West",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/dhfidtn8jrumakbogeu4"
  },
  {
    id: "nfl_Seattle",
    city: "Seattle",
    name: "Seahawks",
    option: "Seahawks",
    abr: "SEA",
    conf: "NFC",
    div: "West",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/gcytzwpjdzbpwnwxincg"
  },
  {
    id: "nfl_San_Francisco",
    city: "San Francisco",
    name: "49ers",
    option: "49ers",
    abr: "SF",
    conf: "NFC",
    div: "West",
    logo: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/dxibuyxbk0b9ua5ih9hn"
  },
  {
    id: "nfl_la_ramss",
    city: "Los Angeless",
    name: "Rams",
    option: "Rams",
    abr: "STL",
    conf: "NFC",
    div: "West",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/ayvwcmluj2ohkdlbiegi"
  },
  {
    id: "nfl_Tampa_Bay",
    city: "Tampa Bay",
    name: "Buccaneers",
    option: "Buccaneers",
    abr: "TB",
    conf: "NFC",
    div: "South",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/v8uqiualryypwqgvwcih"
  },
  {
    id: "nfl_Tennessee",
    city: "Tennessee",
    name: "Titants",
    option: "Titants",
    abr: "TEN",
    conf: "AFC",
    div: "South",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/pln44vuzugjgipyidsre"
  },
  {
    id: "nfl_Washington",
    city: "Washington",
    name: "Redskins",
    option: "Redskins",
    abr: "WAS",
    conf: "NFC",
    div: "East",
    logo: "https://static.www.nfl.com/image/private/f_auto/league/xymxwrxtyj9fhaemhdyd"
  },
];

export const epl_teams = []